name: CosmoBase Auto Cron

on:
  schedule:
    # 毎時 00分 と 30分 に実行する
    - cron: '0,30 * * * *'
  workflow_dispatch: # 手動でテスト実行できるようにするボタン

jobs:
  run-cron:
    runs-on: ubuntu-latest
    steps:
      - name: APIの引き金を引く
        run: curl -X GET "https://cosmo-base-bot.vercel.app/api/cron"